### ISSUE TITLE
Unhandled Exception: Unable to cast object 

### ISSUE THREAD

**Issue by mgorinova** [Microsoft/prose#4]
Hi! I have encounter an unhandled exception which I suppose is due to an explicit cast instead of .ToArray()/.ToList() cast. The problem occurs as follows:

I have a grammar that uses the Map standard concept. So something like:

```
string[] a := A(f, b) = Map(\z:MapArgument => f, b);
MapArgument[] b:= B(....); 
```

Now when I try to synthesise a program, PROSE throws the following exception (stack trace copied at the end): "Unable to cast object of type 'WhereSelectArrayIterator`2[System.Object,System.Object]' to type 'System.String[]'.". 

This looks like there is an explicit cast such as `(string[]) arr` somewhere where it should be `arr.ToArray()`. Indeed, when I change all `string[]` to `IEnumerable<string>` in my grammar and semantics, everything works fine. 

Attached is the exception trace:

```
"Unable to cast object of type 'WhereSelectArrayIterator`2[System.Object,System.Object]' to type 'System.String[]'."

   at lambda_method(Closure , Object[] )
   at Microsoft.ProgramSynthesis.Rules.BlackBoxRule.Evaluate(Object[] args)
   at Microsoft.ProgramSynthesis.AST.NonterminalNode.Evaluate(State state)
   at Microsoft.ProgramSynthesis.AST.ProgramNode.Invoke(State state)
   at Microsoft.ProgramSynthesis.AST.LetNode.Evaluate(State state)
   at Microsoft.ProgramSynthesis.AST.ProgramNode.Invoke(State state)
   at Microsoft.ProgramSynthesis.AST.NonterminalNode.Evaluate(State state)
   at Microsoft.ProgramSynthesis.AST.ProgramNode.Invoke(State state)
   at Microsoft.ProgramSynthesis.VersionSpace.DirectProgramSet.<>c__DisplayClass7_0.<CalculateClusters>b__0(ProgramNode p)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.ProgramSynthesis.VersionSpace.DirectProgramSet.CalculateClusters(State inputState)
   at Microsoft.ProgramSynthesis.VersionSpace.ProgramSet.ClusterOnInput(State inputState)
   at Microsoft.ProgramSynthesis.VersionSpace.ProgramSet.CalculateClusters(State[] inputStates)
   at Microsoft.ProgramSynthesis.VersionSpace.ProgramSet.ClusterOnInputTuple(IEnumerable`1 inputStates)
   at Microsoft.ProgramSynthesis.Learning.Strategies.DeductiveSynthesis.BuildFromDependencies(WitnessingPlan plan, List`1 order, Int32 current, IDictionary`2 graph, ImmutableDictionary`2 prereqsBindings, SynthesisEngine engine, CancellationToken cancel, NonterminalRule rule, LearningTask`1 task)
   at Microsoft.ProgramSynthesis.Learning.Strategies.DeductiveSynthesis.BuildFromDependencies(WitnessingPlan plan, List`1 order, Int32 current, IDictionary`2 graph, ImmutableDictionary`2 prereqsBindings, SynthesisEngine engine, CancellationToken cancel, NonterminalRule rule, LearningTask`1 task)
   at Microsoft.ProgramSynthesis.Learning.Strategies.DeductiveSynthesis.LearnRuleFromWitnesses(SynthesisEngine engine, NonterminalRule rule, LearningTask`1 task, CancellationToken cancel)
   at Microsoft.ProgramSynthesis.Learning.Strategies.DeductiveSynthesis.LearnSymbol(SynthesisEngine engine, LearningTask`1 task, CancellationToken cancel)
   at Microsoft.ProgramSynthesis.Learning.Strategies.SynthesisStrategy`2.Learn(SynthesisEngine engine, LearningTask task, CancellationToken cancel)
   at Microsoft.ProgramSynthesis.Learning.SynthesisEngine.<>c__DisplayClass25_2.<LearnSymbol>b__0()
   at Microsoft.ProgramSynthesis.Learning.SynthesisEngine.InvokeStrategy[TResult](Func`1 learner)
   at Microsoft.ProgramSynthesis.Learning.SynthesisEngine.LearnSymbol(LearningTask task, Nullable`1 cancel)
   at Microsoft.ProgramSynthesis.Learning.Strategies.DeductiveSynthesis.LearnRuleFromWitnesses(SynthesisEngine engine, NonterminalRule rule, LearningTask`1 task, CancellationToken cancel)
   at Microsoft.ProgramSynthesis.Learning.Strategies.DeductiveSynthesis.LearnSymbol(SynthesisEngine engine, LearningTask`1 task, CancellationToken cancel)
   at Microsoft.ProgramSynthesis.Learning.Strategies.SynthesisStrategy`2.Learn(SynthesisEngine engine, LearningTask task, CancellationToken cancel)
   at Microsoft.ProgramSynthesis.Learning.SynthesisEngine.<>c__DisplayClass25_2.<LearnSymbol>b__0()
   at Microsoft.ProgramSynthesis.Learning.SynthesisEngine.InvokeStrategy[TResult](Func`1 learner)
   at Microsoft.ProgramSynthesis.Learning.SynthesisEngine.LearnSymbol(LearningTask task, Nullable`1 cancel)
   at Microsoft.ProgramSynthesis.Learning.SynthesisEngine.LearnSymbol(Symbol symbol, Spec spec, Nullable`1 cancel)
   at Microsoft.ProgramSynthesis.Learning.SynthesisEngine.LearnGrammar(Spec spec, Nullable`1 cancel)
   at Synthesis.Program.Main(String[] args) in z:\Repos\...
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by rndmcnlly** [comment]
Hi @DarkMatter222, we've rewritten the part of the framework that is giving you trouble here in our internal version. However, we still want to make sure this issue doesn't arise in the new version.

Could you tell us a little more about your `f` in this example? Alternatively, is your experiment part of a project we can browse here on GitHub? We can't yet identify which `lambda_method` is in play here.

**Comment by apskim** [comment]
Short answer: this grammar should not work, and it it expected. We should emit a nice compilation error instead of a run-time crash, though — thanks for reporting it! :)

Long answer: as you rightly observed, the types in the grammar don't match. The signature of `Map` is the same as the signature of [LINQ .Select](https://msdn.microsoft.com/en-us/library/bb548891%28v=vs.100%29.aspx?f=255&MSPPError=-2147217396):

```
(Func<T, S> transformer, IEnumerable<T> sequence) -> IEnumerable<S>
```

Since the actual output of `Map` is `IEnumerable<string>`, and `IEnumerable<string>` is not implicitly convertible to `string[]`, the attempted conversion in our compiled synthesizer code fails. Essentially, the situation is equivalent to the following C# code:

``` cs
string[] x = new[] { "foo", "bar" };
string[] y = x.Select(s => s);
```

In this example C# compiler will report a type conversion error. You'll need an explicit `.ToArray()` call to resolve it.

In our case, we could do one of the following:
1. Enable implicit conversions in the framework and execute the call above as if it contains either `.ToArray()` or a `(string[])` cast.
2. Add a new error to `dslc.exe` that forbids compilation of this grammar (or rather, fix its existing type checker to cover this case).

I personally vote for option 2, as option 1 opens a snake pit of "too much magic", IMO. I am a little bit embarrassed that `dslc.exe` doesn't report it as an error already, but we will fix it by the next release ;)

Thanks a lot for the report!

**Comment by simmdan** [comment]
I'm closing the issue based on Alex's follow-up and the fact that we have released newer versions of the framework with a great many changes.  Please don't hesitate to reactivate or open a new issue if you are still encountering difficulty.
